# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.hostname = "PREST-Demo-VM"

  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine and disable USB
    vb.gui = true

  # Customize the amount of memory on the VM:
    vb.memory = "1024"
       vb.name = "PREST-Demo-VM"
       vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
       vb.customize ["modifyvm", :id, "--usb", "off"]
       vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  
  # Run provisioning script
  config.vm.provision :shell, privileged: false, path: "setup.sh"

end
